// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cmd.proto

package cmd

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CounterIncCmd struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Labels               map[string]string `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CounterIncCmd) Reset()         { *m = CounterIncCmd{} }
func (m *CounterIncCmd) String() string { return proto.CompactTextString(m) }
func (*CounterIncCmd) ProtoMessage()    {}
func (*CounterIncCmd) Descriptor() ([]byte, []int) {
	return fileDescriptor_7520252fb01eaf30, []int{0}
}

func (m *CounterIncCmd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CounterIncCmd.Unmarshal(m, b)
}
func (m *CounterIncCmd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CounterIncCmd.Marshal(b, m, deterministic)
}
func (m *CounterIncCmd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CounterIncCmd.Merge(m, src)
}
func (m *CounterIncCmd) XXX_Size() int {
	return xxx_messageInfo_CounterIncCmd.Size(m)
}
func (m *CounterIncCmd) XXX_DiscardUnknown() {
	xxx_messageInfo_CounterIncCmd.DiscardUnknown(m)
}

var xxx_messageInfo_CounterIncCmd proto.InternalMessageInfo

func (m *CounterIncCmd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CounterIncCmd) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

type CounterAddCmd struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Labels               map[string]string `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Value                uint64            `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CounterAddCmd) Reset()         { *m = CounterAddCmd{} }
func (m *CounterAddCmd) String() string { return proto.CompactTextString(m) }
func (*CounterAddCmd) ProtoMessage()    {}
func (*CounterAddCmd) Descriptor() ([]byte, []int) {
	return fileDescriptor_7520252fb01eaf30, []int{1}
}

func (m *CounterAddCmd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CounterAddCmd.Unmarshal(m, b)
}
func (m *CounterAddCmd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CounterAddCmd.Marshal(b, m, deterministic)
}
func (m *CounterAddCmd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CounterAddCmd.Merge(m, src)
}
func (m *CounterAddCmd) XXX_Size() int {
	return xxx_messageInfo_CounterAddCmd.Size(m)
}
func (m *CounterAddCmd) XXX_DiscardUnknown() {
	xxx_messageInfo_CounterAddCmd.DiscardUnknown(m)
}

var xxx_messageInfo_CounterAddCmd proto.InternalMessageInfo

func (m *CounterAddCmd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CounterAddCmd) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *CounterAddCmd) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func init() {
	proto.RegisterType((*CounterIncCmd)(nil), "CounterIncCmd")
	proto.RegisterMapType((map[string]string)(nil), "CounterIncCmd.LabelsEntry")
	proto.RegisterType((*CounterAddCmd)(nil), "CounterAddCmd")
	proto.RegisterMapType((map[string]string)(nil), "CounterAddCmd.LabelsEntry")
}

func init() { proto.RegisterFile("cmd.proto", fileDescriptor_7520252fb01eaf30) }

var fileDescriptor_7520252fb01eaf30 = []byte{
	// 170 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0xce, 0x4d, 0xd1,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x9a, 0xc4, 0xc8, 0xc5, 0xeb, 0x9c, 0x5f, 0x9a, 0x57, 0x92,
	0x5a, 0xe4, 0x99, 0x97, 0xec, 0x9c, 0x9b, 0x22, 0x24, 0xc4, 0xc5, 0x92, 0x97, 0x98, 0x9b, 0x2a,
	0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0x66, 0x0b, 0x19, 0x71, 0xb1, 0xe5, 0x24, 0x26, 0xa5,
	0xe6, 0x14, 0x4b, 0x30, 0x29, 0x30, 0x6b, 0x70, 0x1b, 0x49, 0xe9, 0xa1, 0xe8, 0xd1, 0xf3, 0x01,
	0x4b, 0xba, 0xe6, 0x95, 0x14, 0x55, 0x06, 0x41, 0x55, 0x4a, 0x59, 0x72, 0x71, 0x23, 0x09, 0x0b,
	0x09, 0x70, 0x31, 0x67, 0xa7, 0x56, 0x42, 0x4d, 0x05, 0x31, 0x85, 0x44, 0xb8, 0x58, 0xcb, 0x12,
	0x73, 0x4a, 0x53, 0x25, 0x98, 0xc0, 0x62, 0x10, 0x8e, 0x15, 0x93, 0x05, 0xa3, 0xd2, 0x0a, 0x84,
	0xa3, 0x1c, 0x53, 0x52, 0x48, 0x76, 0x14, 0x44, 0x0f, 0x36, 0x47, 0x21, 0xec, 0x64, 0x56, 0x60,
	0xd4, 0x60, 0x81, 0xda, 0x49, 0x81, 0x53, 0x93, 0xd8, 0xc0, 0xc1, 0x68, 0x0c, 0x08, 0x00, 0x00,
	0xff, 0xff, 0xb1, 0x6c, 0x88, 0x82, 0x53, 0x01, 0x00, 0x00,
}
