// Code generated by protoc-gen-go. DO NOT EDIT.
// source: payload.proto

package payload

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CounterIncCmd struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Labels               map[string]string `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CounterIncCmd) Reset()         { *m = CounterIncCmd{} }
func (m *CounterIncCmd) String() string { return proto.CompactTextString(m) }
func (*CounterIncCmd) ProtoMessage()    {}
func (*CounterIncCmd) Descriptor() ([]byte, []int) {
	return fileDescriptor_678c914f1bee6d56, []int{0}
}

func (m *CounterIncCmd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CounterIncCmd.Unmarshal(m, b)
}
func (m *CounterIncCmd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CounterIncCmd.Marshal(b, m, deterministic)
}
func (m *CounterIncCmd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CounterIncCmd.Merge(m, src)
}
func (m *CounterIncCmd) XXX_Size() int {
	return xxx_messageInfo_CounterIncCmd.Size(m)
}
func (m *CounterIncCmd) XXX_DiscardUnknown() {
	xxx_messageInfo_CounterIncCmd.DiscardUnknown(m)
}

var xxx_messageInfo_CounterIncCmd proto.InternalMessageInfo

func (m *CounterIncCmd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CounterIncCmd) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

type CounterAddCmd struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Labels               map[string]string `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Value                uint64            `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CounterAddCmd) Reset()         { *m = CounterAddCmd{} }
func (m *CounterAddCmd) String() string { return proto.CompactTextString(m) }
func (*CounterAddCmd) ProtoMessage()    {}
func (*CounterAddCmd) Descriptor() ([]byte, []int) {
	return fileDescriptor_678c914f1bee6d56, []int{1}
}

func (m *CounterAddCmd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CounterAddCmd.Unmarshal(m, b)
}
func (m *CounterAddCmd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CounterAddCmd.Marshal(b, m, deterministic)
}
func (m *CounterAddCmd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CounterAddCmd.Merge(m, src)
}
func (m *CounterAddCmd) XXX_Size() int {
	return xxx_messageInfo_CounterAddCmd.Size(m)
}
func (m *CounterAddCmd) XXX_DiscardUnknown() {
	xxx_messageInfo_CounterAddCmd.DiscardUnknown(m)
}

var xxx_messageInfo_CounterAddCmd proto.InternalMessageInfo

func (m *CounterAddCmd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CounterAddCmd) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *CounterAddCmd) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type HealthBit struct {
	Ttl                  uint64   `protobuf:"varint,1,opt,name=ttl,proto3" json:"ttl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthBit) Reset()         { *m = HealthBit{} }
func (m *HealthBit) String() string { return proto.CompactTextString(m) }
func (*HealthBit) ProtoMessage()    {}
func (*HealthBit) Descriptor() ([]byte, []int) {
	return fileDescriptor_678c914f1bee6d56, []int{2}
}

func (m *HealthBit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthBit.Unmarshal(m, b)
}
func (m *HealthBit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthBit.Marshal(b, m, deterministic)
}
func (m *HealthBit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthBit.Merge(m, src)
}
func (m *HealthBit) XXX_Size() int {
	return xxx_messageInfo_HealthBit.Size(m)
}
func (m *HealthBit) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthBit.DiscardUnknown(m)
}

var xxx_messageInfo_HealthBit proto.InternalMessageInfo

func (m *HealthBit) GetTtl() uint64 {
	if m != nil {
		return m.Ttl
	}
	return 0
}

type ReadyBit struct {
	Ttl                  uint64   `protobuf:"varint,1,opt,name=ttl,proto3" json:"ttl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadyBit) Reset()         { *m = ReadyBit{} }
func (m *ReadyBit) String() string { return proto.CompactTextString(m) }
func (*ReadyBit) ProtoMessage()    {}
func (*ReadyBit) Descriptor() ([]byte, []int) {
	return fileDescriptor_678c914f1bee6d56, []int{3}
}

func (m *ReadyBit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadyBit.Unmarshal(m, b)
}
func (m *ReadyBit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadyBit.Marshal(b, m, deterministic)
}
func (m *ReadyBit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadyBit.Merge(m, src)
}
func (m *ReadyBit) XXX_Size() int {
	return xxx_messageInfo_ReadyBit.Size(m)
}
func (m *ReadyBit) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadyBit.DiscardUnknown(m)
}

var xxx_messageInfo_ReadyBit proto.InternalMessageInfo

func (m *ReadyBit) GetTtl() uint64 {
	if m != nil {
		return m.Ttl
	}
	return 0
}

func init() {
	proto.RegisterType((*CounterIncCmd)(nil), "CounterIncCmd")
	proto.RegisterMapType((map[string]string)(nil), "CounterIncCmd.LabelsEntry")
	proto.RegisterType((*CounterAddCmd)(nil), "CounterAddCmd")
	proto.RegisterMapType((map[string]string)(nil), "CounterAddCmd.LabelsEntry")
	proto.RegisterType((*HealthBit)(nil), "HealthBit")
	proto.RegisterType((*ReadyBit)(nil), "ReadyBit")
}

func init() { proto.RegisterFile("payload.proto", fileDescriptor_678c914f1bee6d56) }

var fileDescriptor_678c914f1bee6d56 = []byte{
	// 208 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x48, 0xac, 0xcc,
	0xc9, 0x4f, 0x4c, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x9a, 0xc4, 0xc8, 0xc5, 0xeb, 0x9c,
	0x5f, 0x9a, 0x57, 0x92, 0x5a, 0xe4, 0x99, 0x97, 0xec, 0x9c, 0x9b, 0x22, 0x24, 0xc4, 0xc5, 0x92,
	0x97, 0x98, 0x9b, 0x2a, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0x66, 0x0b, 0x19, 0x71, 0xb1,
	0xe5, 0x24, 0x26, 0xa5, 0xe6, 0x14, 0x4b, 0x30, 0x29, 0x30, 0x6b, 0x70, 0x1b, 0x49, 0xe9, 0xa1,
	0xe8, 0xd1, 0xf3, 0x01, 0x4b, 0xba, 0xe6, 0x95, 0x14, 0x55, 0x06, 0x41, 0x55, 0x4a, 0x59, 0x72,
	0x71, 0x23, 0x09, 0x0b, 0x09, 0x70, 0x31, 0x67, 0xa7, 0x56, 0x42, 0x4d, 0x05, 0x31, 0x85, 0x44,
	0xb8, 0x58, 0xcb, 0x12, 0x73, 0x4a, 0x53, 0x25, 0x98, 0xc0, 0x62, 0x10, 0x8e, 0x15, 0x93, 0x05,
	0xa3, 0xd2, 0x0a, 0x84, 0xa3, 0x1c, 0x53, 0x52, 0x48, 0x76, 0x14, 0x44, 0x0f, 0x36, 0x47, 0x21,
	0xec, 0x64, 0x56, 0x60, 0xd4, 0x60, 0x81, 0xda, 0x49, 0x89, 0x53, 0x65, 0xb9, 0x38, 0x3d, 0x52,
	0x13, 0x73, 0x4a, 0x32, 0x9c, 0x32, 0x4b, 0x40, 0x1a, 0x4b, 0x4a, 0x72, 0xc0, 0x1a, 0x59, 0x82,
	0x40, 0x4c, 0x25, 0x19, 0x2e, 0x8e, 0xa0, 0xd4, 0xc4, 0x94, 0x4a, 0xac, 0xb2, 0x49, 0x6c, 0xe0,
	0x38, 0x30, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xb5, 0x68, 0x52, 0x85, 0x94, 0x01, 0x00, 0x00,
}
